#!/bin/bash
#
#SBATCH --chdir=/path/to/directory/where/all/the/trimmed/data/is/stored/trimmed_file
#SBATCH --job-name=fastqc
#SBATCH --partition=medium
#SBATCH --cpus-per-task=6
#SBATCH --mem=24G
#SBATCH --export=ALL
#SBATCH --mail-user=email@kew.org
#SBATCH --mail-type=END,FAIL

# Loop through all fastq.gz files in the current directory and run fastqc on each
for f in *.fastq.gz; 
do 
    (fastqc $f); 
done

# Create a directory for storing fastqc results after trimming
mkdir /path/to/directory/where/all/the/trimmed/data/is/stored/trimmed_file/fastqc_post_trim

# Move all zip files generated by fastqc to the new directory
mv *.zip /path/to/directory/where/all/the/trimmed/data/is/stored/trimmed_file/fastqc_post_trim

# Move all HTML files generated by fastqc to the new directory
mv *.html /path/to/directory/where/all/the/trimmed/data/is/stored/trimmed_file/fastqc_post_trim

# Use MultiQC to aggregate Quality Control (QC) data for all samples,
# providing consolidated and informative output files in a centralised location.
multiqc ./
